# Generated by Django 3.2 on 2021-04-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_blockeddays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedDays',
            new_name='BlockedDay',
        ),
    ]
