# Generated by Django 3.2 on 2021-04-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_blockeddays_blockedday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedday',
            name='hotel_room_type',
        ),
        migrations.AddField(
            model_name='blockedday',
            name='hotel_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_day_hr', to='listings.hotelroom'),
        ),
        migrations.AlterField(
            model_name='blockedday',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_day_listing', to='listings.listing'),
        ),
    ]
