# Generated by Django 3.2 on 2021-04-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210429_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedday',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_day_hr', to='listings.hotelroom'),
        ),
        migrations.AlterField(
            model_name='blockedday',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_day_listing', to='listings.listing'),
        ),
    ]
