# Generated by Django 3.2 on 2021-04-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210429_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='hotel_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.hotelroomtype'),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.listing'),
        ),
    ]
